let c = prompt('выбери текст для заголовка')
let d = prompt('выбери цвет для заголовка')
let e = prompt('выбери текст для параграфа')
let f = prompt('выбери цвет для параграфа')
let a = document.getElementById('a')
let b = document.getElementById('b')
a.innerHTML = '<h1>' + c + '</h1>'
a.style.color = d
b.innerHTML = e
b.style.color = f
